name = "example"

[attributes.id]
source = "raw_first.id"
fn = "int->int"

[attributes.time]
source = "raw_first.created_at"
fn = "int->int"

[attributes.first]
source = "raw_first.value"
fn = "string->string"

[attributes.second]
source = "raw_second.value"
fn = "string->int"