name = "example"

[attributes.id]
fn = "com.angelini.starbeam.udfs.Base/identity"

    [attributes.id.sources.raw_first]
    table = "raw_first"
    column = "id"

[attributes.time]
fn = "com.angelini.starbeam.udfs.Base/identity"

    [attributes.time.sources.raw_first]
    table = "raw_first"
    column = "created_at"

[attributes.first]
fn = "com.angelini.starbeam.udfs.Base/identity"

    [attributes.first.sources.raw_first]
    table = "raw_first"
    column = "value"

[attributes.second]
fn = "com.angelini.starbeam.udfs.Base/stringToInt"

    [attributes.second.sources.raw_second]
    table = "raw_second"
    column = "value"
