name = "example"

[attributes.id]
source = "raw_first.id"
fn = "com.angelini.starbeam.udfs.Base/identity"

[attributes.time]
source = "raw_first.created_at"
fn = "com.angelini.starbeam.udfs.Base/identity"

[attributes.first]
source = "raw_first.value"
fn = "com.angelini.starbeam.udfs.Base/identity"

[attributes.second]
source = "raw_second.value"
fn = "com.angelini.starbeam.udfs.Base/stringToInt"